package Services;

import com.itextpdf.text.*;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;

import Entite.House;
import Entite.Personne;
import Entite.Reservation;
import javafx.collections.ObservableList; // Import nécessaire pour ObservableList

import java.io.FileOutputStream;
import java.io.IOException;
import java.util.Date;

public class PdfExportService {

    private static Font catFont = new Font(Font.FontFamily.TIMES_ROMAN, 18, Font.BOLD);
    private static Font subFont = new Font(Font.FontFamily.TIMES_ROMAN, 16, Font.BOLD);
    private static Font redFont = new Font(Font.FontFamily.TIMES_ROMAN, 12, Font.NORMAL, BaseColor.RED);
    private static Font smallBold = new Font(Font.FontFamily.TIMES_ROMAN, 12, Font.BOLD);

    // Méthode principale pour générer un PDF (si vous ne voulez pas de table spécifique)
    public void generatePdf(String fileName) throws DocumentException, IOException {
        Document document = new Document();
        PdfWriter.getInstance(document, new FileOutputStream(fileName));
        document.open();
        addMetaData(document);
        addTitlePage(document);
        addContent(document);
        document.close();
    }

    // Méthode pour ajouter des métadonnées au document PDF
    private void addMetaData(Document document) {
        document.addTitle("My first PDF");
        document.addSubject("Using iText");
        document.addKeywords("Java, PDF, iText");
        document.addAuthor("Your Name");
        document.addCreator("Your Application");
    }

    // Méthode pour ajouter une page de titre
    private void addTitlePage(Document document) throws DocumentException {
        Paragraph preface = new Paragraph();
        addEmptyLine(preface, 1);
        preface.add(new Paragraph("MyBooking.com", catFont));
        addEmptyLine(preface, 1);
        preface.add(new Paragraph("Report generated by: " + System.getProperty("user.name") + ", " + new Date(), smallBold));
        addEmptyLine(preface, 3);
        preface.add(new Paragraph("This document describes something important.", smallBold));
        addEmptyLine(preface, 8);
        preface.add(new Paragraph("This document is preliminary and not subject to any license agreement.", redFont));

        document.add(preface);
        document.newPage();
    }

    // Méthode pour ajouter du contenu au document PDF
    private void addContent(Document document) throws DocumentException {
        Anchor anchor = new Anchor("First Chapter", catFont);
        anchor.setName("First Chapter");
        Chapter catPart = new Chapter(new Paragraph(anchor), 1);

        Paragraph subPara = new Paragraph("Subcategory 1", subFont);
        Section subCatPart = catPart.addSection(subPara);
        subCatPart.add(new Paragraph("Hello"));

        subPara = new Paragraph("Subcategory 2", subFont);
        subCatPart = catPart.addSection(subPara);
        subCatPart.add(new Paragraph("Paragraph 1"));
        subCatPart.add(new Paragraph("Paragraph 2"));
        subCatPart.add(new Paragraph("Paragraph 3"));

        createTable(subCatPart);
        createList(subCatPart);
        document.add(catPart);
    }

    // Méthode pour créer un tableau simple dans le PDF
    private void createTable(Section subCatPart) throws BadElementException {
        PdfPTable table = new PdfPTable(3);
        table.addCell("Table Header 1");
        table.addCell("Table Header 2");
        table.addCell("Table Header 3");
        table.setHeaderRows(1);
        table.addCell("1.0");
        table.addCell("1.1");
        table.addCell("1.2");
        subCatPart.add(table);
    }

    // Méthode pour ajouter une liste simple
    private void createList(Section subCatPart) {
        List list = new List(true, false, 10);
        list.add(new ListItem("First point"));
        list.add(new ListItem("Second point"));
        list.add(new ListItem("Third point"));
        subCatPart.add(list);
    }

    // Méthode pour ajouter des lignes vides dans un paragraphe
    private void addEmptyLine(Paragraph paragraph, int number) {
        for (int i = 0; i < number; i++) {
            paragraph.add(new Paragraph(" "));
        }
    }

    // Méthode pour générer un PDF avec un tableau des personnes
    public void generatePdfTable(String fileName, ObservableList<Personne> personnes) throws DocumentException, IOException {
        Document document = new Document();
        PdfWriter.getInstance(document, new FileOutputStream(fileName));
        document.open();
        addMetaData(document);
        addTitlePage(document);
        //addContent(document);
        // Titre du document
        Font titleFont = new Font(Font.FontFamily.HELVETICA, 18, Font.BOLD);
        Paragraph title = new Paragraph("Liste des Personnes \n", titleFont);
        title.setAlignment(Paragraph.ALIGN_CENTER);
        document.add(title);

        // Ajouter un tableau pour les données
        PdfPTable table = new PdfPTable(6); // 6 colonnes pour ID, Nom, Prenom, Cin, Address, Email
        table.addCell("ID");
        table.addCell("Nom");
        table.addCell("Prenom");
        table.addCell("CIN");
        table.addCell("Address");
        table.addCell("Email");

        // Remplir le tableau avec les données
        for (Personne personne : personnes) {
            table.addCell(String.valueOf(personne.getId()));
            table.addCell(personne.getNom());
            table.addCell(personne.getPrenom());
            table.addCell(personne.getCin());
            table.addCell(personne.getAddress());
            table.addCell(personne.getEmail());
        }

        document.add(table);
        document.close();
    }

    public void generateHousePdfTable(String fileName, ObservableList<House> houses) throws DocumentException, IOException {
        Document document = new Document();
        PdfWriter.getInstance(document, new FileOutputStream(fileName));
        document.open();
        addMetaData(document);
        addTitlePage(document);
    
        // Titre du document
        Font titleFont = new Font(Font.FontFamily.HELVETICA, 18, Font.BOLD);
        Paragraph title = new Paragraph("Liste des Maisons \n", titleFont);
        title.setAlignment(Paragraph.ALIGN_CENTER);
        document.add(title);
    
        // Ajouter un tableau pour les données
        PdfPTable table = new PdfPTable(7); // 7 colonnes pour ID, Nom, Localisation, Chambres, Prix, Capacité, Réservé
        table.addCell("ID");
        table.addCell("Nom");
        table.addCell("Localisation");
        table.addCell("Chambres Disponibles (s+?)");
        table.addCell("Prix par Jour");
        table.addCell("Capacité Totale");
        table.addCell("Réservé par notre Agence");

        // Remplir le tableau avec les données
        for (House house : houses) {
            table.addCell(String.valueOf(house.getId())); // Convertir en String
            table.addCell(house.getName());
            table.addCell(house.getLocation());
            table.addCell(String.valueOf(house.getRoomsAvailable())); // Convertir en String
            table.addCell(String.valueOf(house.getPricePerNight())); // Convertir en String
            table.addCell(house.getFullCapacity());
            table.addCell(house.getReservedByOurAgency());
        }
    
        document.add(table);
        document.close();
    }

    public void generateReservationReceipt(String fileName, Reservation reservation) throws DocumentException, IOException {
        Document document = new Document();
        PdfWriter.getInstance(document, new FileOutputStream(fileName));
        document.open();
        addTitlePage(document);
        Paragraph preface = new Paragraph();
        addEmptyLine(preface, 1);
        // Ajouter un titre
        Font titleFont = new Font(Font.FontFamily.HELVETICA, 18, Font.BOLD);
        Paragraph title = new Paragraph("Reçu de Réservation\n", titleFont);
        title.setAlignment(Paragraph.ALIGN_CENTER);
        document.add(title);

        // Ajouter les détails de la réservation
        document.add(new Paragraph("Nom: " + reservation.getUserFullName()));
        document.add(new Paragraph("Email: " + reservation.getUserEmail()));
        document.add(new Paragraph("Maison ID: " + reservation.getId()));
        document.add(new Paragraph("Date de début: " + reservation.getDateDebut()));
        document.add(new Paragraph("Date de fin: " + reservation.getDateFin()));
        document.add(new Paragraph("Prix total: " + String.format("%.2f DT", reservation.getReservationPrice())));
        document.add(new Paragraph("\nDate de génération: " + new Date()));

        document.close();
    }
}
